[build]
  base = "sybertnetics-website"
  publish = ".next"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"

# Enable form processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Handle specific page redirects to ensure consistency
[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/thank-you"
  to = "/thank-you/"
  status = 301

# Ensure form processing works
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
