[build]
  publish = "sybertnetics-website/out"
  command = "cd sybertnetics-website && npm install && npm run build"

# Enable form processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Handle specific page redirects to ensure consistency
[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/thank-you"
  to = "/thank-you/"
  status = 301

# SPA redirect for all other routes (except existing files)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure form processing works
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
