# This is the single source of truth for your Netlify build settings.

[build]
  # We specify the base directory, so Netlify runs the build from here.
  base = "sybertnetics-website"
  # The publish directory for a standard Next.js build is .next
  publish = ".next"
  # The build command remains the same.
  command = "npm install && npm run build"

# The functions directory is relative to the base directory.
[functions]
  directory = "netlify/functions"

# The Next.js plugin is essential for handling routing, SSR, etc.
[[plugins]]
  package = "@netlify/plugin-nextjs"
