[build]
  publish = "sybertnetics-website/out"
  command = "cd sybertnetics-website && npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
