[build]
  publish = "out"
  command = "cd sybertnetics-website && npm install && npm run build"
  functions = "sybertnetics-website/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Forms
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Form processing settings
[build.processing]
  skip_processing = false

# Handle redirects
[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/thank-you"
  to = "/thank-you/"
  status = 301

# Headers for static assets
[[headers]]
  for = "/_next/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 